baseURL = 'https://example.org/'
title = '曲陵札記'
languageCode = 'zh-CN'
theme = 'hugo-theme-reimu'

defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '现代汉语'
weight = 1
hasCJKLanguage = true
[languages.lzh]
languageName = '文言文'
weight = 2
hasCJKLanguage = true
[languages.ko]
languageName = '한국어(한글)'
weight = 3
hasCJKLanguage = true
[languages.oko]
languageName = '國漢文/한글'
weight = 4
hasCJKLanguage = true
[languages.ja]
languageName = '日本語'
weight = 5
hasCJKLanguage = true
[languages.en]
languageName = 'English'
weight = 6


[params.poetry]
enable = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
